apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-app
spec:
  replicas: 2  # Number of pods
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
      - name: calculator
        image: gayathri731/calculator:latest  # Replace with your Docker Hub image
        ports:
        - containerPort: 5000  # Change if needed

